<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Reservation;

/**
 * ReservationCustomerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
