<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Attribute;

/**
 * AttributeSetInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeSetInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
