<?php

namespace Pasteque\Bundle\ServerBundle\Repository;

/**
 * AttributeInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
