<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Cash;

/**
 * CashMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
