<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Product;

/**
 * ProductComRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductComRepository extends \Doctrine\ORM\EntityRepository
{
}
