Pasteque\Bundle\ServerBundle\Entity\AttributeSet:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\AttributeSetRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
