Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeValue:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeValueRepository
    id:
        id:
            type: string
            length: 255
    fields:
        value:
            type: string
            length: 255
    lifecycleCallbacks: {  }
