Pasteque\Bundle\ServerBundle\Entity\Attribute\Attribute:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        name:
            type: string
            length: 255
        displayOrder:
            type: integer
        active:
            type: boolean
        addedDate:
            type: datetime
        addedBy:
            type: string
            length: 255
        updatedDate:
            type: datetime
            nullable: true
        updatedBy:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
