Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeInstance:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeInstanceRepository
    id:
        id:
            type: string
            length: 255
    fields:
        attrSetInstId:
            type: string
            length: 255
        attrId:
            type: string
            length: 255
        value:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
