Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeSetInstance:
    type: entity
    manyToOne:
        attributeSetId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeSet
            orphanRemoval: true
            joinColumn:
                name: attributeset_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeSetInstanceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        attrSetId:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
