Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeValue:
    type: entity
    manyToOne:
        attributeId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeValue
            orphanRemoval: true
            joinColumn:
                name: attribute_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeValueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        value:
            type: string
            length: 255
    lifecycleCallbacks: {  }
