Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeSet:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeSetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
