Pasteque\Bundle\ServerBundle\Entity\Attribute\Attribute:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
        displayOrder:
            type: integer
        active:
            type: tinyint
        addedDate:
            type: datetime
        addedBy:
            type: string
            length: 255
        updatedDate:
            type: datetime
        updatedBy:
            type: string
            length: 255
    lifecycleCallbacks: {  }
