Pasteque\Bundle\ServerBundle\Entity\AttributeUse:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\AttributeUseRepository
    id:
        id:
            type: string
            length: 255
    fields:
        attrSetId:
            type: string
            length: 255
        attrId:
            type: string
            length: 255
        lineNo:
            type: integer
    lifecycleCallbacks: {  }
