Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeUse:
    type: entity
    manyToOne:
        attributeSetId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeSet
            orphanRemoval: true
            joinColumn:
                name: attributeset_id
                referencedColumnName: id
        attributeId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Attribute\Attribute
            joinColumn:
                name: attribute_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeUseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        attrSetId:
            type: string
            length: 255
        attrId:
            type: string
            length: 255
        lineNo:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
