Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeInstance:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Attribute\AttributeInstanceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        value:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
