Pasteque\Bundle\ServerBundle\Entity\Cash\Cash:
    type: entity
    manyToOne:
        cashRegisterId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Cash\CashRegister
            joinColumn:
                name: cashregister_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Cash\CashRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        money:
            type: string
            length: 255
        cashRegisterId:
            type: string
            length: 255
        hostSequence:
            type: integer
        openDate:
            type: datetime
        closeDate:
            type: datetime
        openCash:
            type: float
        closeCash:
            type: float
        expectedCash:
            type: float
    lifecycleCallbacks: {  }
