Pasteque\Bundle\ServerBundle\Entity\Cash\CashRegister:
    type: entity
    manyToOne:
        locationId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Location
            joinColumn:
                name: location_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Cash\CashRegisterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
