Pasteque\Bundle\ServerBundle\Entity\Category:
    type: entity
    oneToOne:
        parentId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Category
            joinColumn:
                name: parent_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        name:
            type: string
            length: 255
            unique: true
        reference:
            type: string
            length: 255
            nullable: true
        parentId:
            type: integer
            nullable: true
        image:
            type: blob
            nullable: true
        displayOrder:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
