Pasteque\Bundle\ServerBundle\Entity\Customer:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\CustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        displayName:
            type: string
            length: 255
        searchKey:
            type: string
            length: 255
            nullable: true
        number:
            type: integer
            nullable: true
        customerTaxCategoryId:
            type: string
            length: 255
            nullable: true
        discountProfileId:
            type: integer
            nullable: true
        tariffAreaId:
            type: integer
            nullable: true
        card:
            type: string
            length: 255
            nullable: true
        maxDebt:
            type: float
        prepaid:
            type: float
        currentDebt:
            type: float
            nullable: true
        debtDate:
            type: datetime
            nullable: true
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        phone2:
            type: string
            length: 255
            nullable: true
        fax:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        address2:
            type: string
            length: 255
            nullable: true
        postal:
            type: string
            length: 255
            nullable: true
        region:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
        expireDate:
            type: datetime
            nullable: true
        note:
            type: text
            nullable: true
        visible:
            type: boolean
    lifecycleCallbacks: {  }
