Pasteque\Bundle\ServerBundle\Entity\Floor:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\FloorRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
            unique: true
        image:
            type: blob
            nullable: true
    lifecycleCallbacks: {  }
