Pasteque\Bundle\ServerBundle\Entity\Group\SubGroup:
    type: entity
    manyToOne:
        groupId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Group\Group
            orphanRemoval: true
            joinColumn:
                name: group_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Group\SubGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        required:
            type: boolean
        image:
            type: blob
            nullable: true
        displayOrder:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
