Pasteque\Bundle\ServerBundle\Entity\Location:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\LocationRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
            unique: true
        address:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
