Pasteque\Bundle\ServerBundle\Entity\Order\OrderLine:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Order\OrderLineRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        line:
            type: integer
            nullable: true
        quantity:
            type: float
            nullable: true
        attributes:
            type: blob
            nullable: true
    lifecycleCallbacks: {  }
