Pasteque\Bundle\ServerBundle\Entity\Payment\PaymentModeReturn:
    type: entity
    manyToOne:
        paymentModeId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Payment\PaymentMode
            joinColumn:
                name: paymentmode_id
                referencedColumnName: id
        paymentReturnModeId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Payment\PaymentMode
            joinColumn:
                name: paymentreturnmode_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Payment\PaymentModeReturnRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        paymentModeId:
            type: integer
        returnModeId:
            type: integer
            nullable: true
        min:
            type: float
    lifecycleCallbacks: {  }
