Pasteque\Bundle\ServerBundle\Entity\Payment\Payment:
    type: entity
    oneToOne:
        pairedPaymentId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Payment\Payment
            orphanRemoval: true
            joinColumn:
                name: pairedPayment_id
                referencedColumnName: id
    manyToOne:
        receiptId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Ticket\Receipt
            joinColumn:
                name: receipt_id
                referencedColumnName: id
       currencyId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Currency
            joinColumn:
                name: currency_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Payment\PaymentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        pairedPaymentId:
            type: integer
        type:
            type: string
            length: 255
        amount:
            type: float
        currencyId:
            type: integer
        currencyAmount:
            type: float
        backType:
            type: string
            length: 255
            nullable: true
        backAmount:
            type: float
            nullable: true
        returnMessage:
            type: blob
            nullable: true
        pairedWith:
            type: string
            length: 255
            nullable: true
        note:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
