Pasteque\Bundle\ServerBundle\Entity\Payment\PaymentModeReturn:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Payment\PaymentModeReturnRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        paymentModeId:
            type: integer
        returnModeId:
            type: integer
            nullable: true
        min:
            type: float
    lifecycleCallbacks: {  }
