Pasteque\Bundle\ServerBundle\Entity\Payment\PaymentModeValue:
    type: entity
    manyToOne:
        paymentModeId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Payment\PaymentMode
            joinColumn:
                name: paymentmode_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Payment\PaymentModeValueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        paymentModeId:
            type: integer
        value:
            type: float
        resource:
            type: string
            length: 255
            nullable: true
        displayOrder:
            type: integer
    lifecycleCallbacks: {  }
