Pasteque\Bundle\ServerBundle\Entity\Place:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\PlaceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        name:
            type: string
            length: 255
            unique: true
        'x':
            type: integer
        'y':
            type: integer
    lifecycleCallbacks: {  }
