Pasteque\Bundle\ServerBundle\Entity\Product\Product:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Product\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        reference:
            type: string
            length: 255
            unique: true
        barcode:
            type: string
            length: 255
            nullable: true
        barcodeType:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
        priceBuy:
            type: float
            nullable: true
        priceSell:
            type: float
        stockCost:
            type: float
            nullable: true
        stockVolume:
            type: float
            nullable: true
        image:
            type: blob
            nullable: true
        isCom:
            type: boolean
        isScale:
            type: boolean
        attributes:
            type: blob
            nullable: true
        discountEnabled:
            type: boolean
        discountRate:
            type: float
        visible:
            type: boolean
    lifecycleCallbacks: {  }
