Pasteque\Bundle\ServerBundle\Entity\Product\ProductCom:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Product\ProductComRepository
    id:
        id:
            type: string
            length: 255
    fields:
        productId:
            type: string
            length: 255
        productId2:
            type: string
            length: 255
    lifecycleCallbacks: {  }
