Pasteque\Bundle\ServerBundle\Entity\Product\ProductCom:
    type: entity
    manyToOne:
        productId1:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Product\Product
            joinColumn:
                name: product_1_id
                referencedColumnName: id
        productId2:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Product\Product
            joinColumn:
                name: product_2_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Product\ProductComRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        productId:
            type: string
            length: 255
        productId2:
            type: string
            length: 255
    lifecycleCallbacks: {  }
