Pasteque\Bundle\ServerBundle\Entity\Product\Product:
    type: entity
    manyToOne:
        categoryId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Category
            joinColumn:
                name: category_id
                referencedColumnName: id
        taxCategoryId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Tax\TaxCategory
            joinColumn:
                name: taxcategory_id
                referencedColumnName: id
        attributeSetId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeSet
            joinColumn:
                name: attributeset_id
                referencedColumnName: id
        providerId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Provider
            joinColumn:
                name: provider_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Product\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        reference:
            type: string
            length: 255
            unique: true
        barcode:
            type: string
            length: 255
            nullable: true
        barcodeType:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
        priceBuy:
            type: float
            nullable: true
        priceSell:
            type: float
        categoryId:
            type: string
            length: 255
        providerId:
            type: string
            length: 255
            nullable: true
        taxCatId:
            type: string
            length: 255
        attributeSetId:
            type: string
            length: 255
        stockCost:
            type: float
            nullable: true
        stockVolume:
            type: float
            nullable: true
        image:
            type: blob
            nullable: true
        isCom:
            type: boolean
        isScale:
            type: boolean
        attributes:
            type: blob
            nullable: true
        discountEnabled:
            type: boolean
        discountRate:
            type: float
        visible:
            type: boolean
    lifecycleCallbacks: {  }
