Pasteque\Bundle\ServerBundle\Entity\Reservation\ReservationCustomer:
    type: entity
    manyToOne:
        reservationId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Reservation\Reservation
            joinColumn:
                name: reservation_id
                referencedColumnName: id
        customerId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Customer
            joinColumn:
                name: customer_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Reservation\ReservationCustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
    lifecycleCallbacks: {  }
