Pasteque\Bundle\ServerBundle\Entity\Resource:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\ResourceRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
            unique: true
        type:
            type: integer
        content:
            type: blob
            nullable: true
    lifecycleCallbacks: {  }
