Pasteque\Bundle\ServerBundle\Entity\Resource:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\ResourceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        name:
            type: string
            length: 255
            unique: true
        type:
            type: integer
        content:
            type: blob
            nullable: true
    lifecycleCallbacks: {  }
