Pasteque\Bundle\ServerBundle\Entity\Stock\StockCurrent:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Stock\StockCurrentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: float
    lifecycleCallbacks: {  }
