Pasteque\Bundle\ServerBundle\Entity\Stock\StockLevel:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Stock\StockLevelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        security:
            type: float
            nullable: true
        max:
            type: float
            nullable: true
        quantity:
            type: float
            nullable: true
    lifecycleCallbacks: {  }
