Pasteque\Bundle\ServerBundle\Entity\Stock\StockMove:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Stock\StockMoveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        date:
            type: datetime
        reason:
            type: integer
        quantity:
            type: float
        price:
            type: float
    lifecycleCallbacks: {  }
