Pasteque\Bundle\ServerBundle\Entity\Stock\StockMove:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Stock\StockMoveRepository
    id:
        id:
            type: string
            length: 255
    fields:
        date:
            type: datetime
        reason:
            type: integer
        locationId:
            type: string
            length: 255
        productId:
            type: string
            length: 255
        attributeSetInstanceId:
            type: string
            length: 255
            nullable: true
        quantity:
            type: float
        price:
            type: float
    lifecycleCallbacks: {  }
