Pasteque\Bundle\ServerBundle\Entity\Stock\StockCurrent:
    type: entity
    manyToOne:
        productId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Product\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
        attributeSetInstanceId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeSetInstance
            joinColumn:
                name: attributesetinstance_id
                referencedColumnName: id
        locationId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Location
            joinColumn:
                name: location_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Stock\StockCurrentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: float
    lifecycleCallbacks: {  }
