Pasteque\Bundle\ServerBundle\Entity\Tax\TaxLine:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Tax\TaxLineRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        receiptId:
            type: string
            length: 255
        taxId:
            type: string
            length: 255
        base:
            type: float
        amount:
            type: float
    lifecycleCallbacks: {  }
