Pasteque\Bundle\ServerBundle\Entity\Tax\TaxCustomerCategory:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Tax\TaxCustomerCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        name:
            type: string
            length: 255
            unique: true
        taxCategoryId:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
