Pasteque\Bundle\ServerBundle\Entity\Tax\TaxLine:
    type: entity
    manyToOne:
        taxId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Tax\Tax
            joinColumn:
                name: tax_id
                referencedColumnName: id
        receiptId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Ticket\Receipt
            joinColumn:
                name: receipt_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Tax\TaxLineRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        receiptId:
            type: string
            length: 255
        taxId:
            type: string
            length: 255
        base:
            type: float
        amount:
            type: float
    lifecycleCallbacks: {  }
