Pasteque\Bundle\ServerBundle\Entity\Ticket\SharedTicketLine:
    type: entity
    manyToOne:
        sharedTicketId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Ticket\SharedTicket
            orphanRemoval: true
            joinColumn:
                name: sharedticket_id
                referencedColumnName: id
        productId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Product\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
        taxId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Tax\Tax
            joinColumn:
                name: tax_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Ticket\SharedTicketLineRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        line:
            type: integer
        quantity:
            type: float
        discountRate:
            type: float
            nullable: true
        price:
            type: float
            nullable: true
        attributes:
            type: blob
            nullable: true
    lifecycleCallbacks: {  }
