Pasteque\Bundle\ServerBundle\Entity\Ticket\SharedTicket:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Ticket\SharedTicketRepository
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
        customerId:
            type: string
            length: 255
            nullable: true
        customerCount:
            type: integer
            nullable: true
        tariffAreaId:
            type: integer
            nullable: true
        discountProfileId:
            type: integer
            nullable: true
        discountRate:
            type: float
            nullable: true
    lifecycleCallbacks: {  }
