Pasteque\Bundle\ServerBundle\Entity\Ticket\Receipt:
    type: entity
    manyToOne:
        cashId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Cash\Cash
            joinColumn:
                name: cash_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Ticket\ReceiptRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        date:
            type: datetime
        attributes:
            type: blob
            nullable: true
    lifecycleCallbacks: {  }
