Pasteque\Bundle\ServerBundle\Entity\Ticket\Ticket:
    type: entity
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Ticket\TicketRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: integer
        date:
            type: datetime
            nullable: true
        status:
            type: integer
        customerCount:
            type: integer
            nullable: true
        discountRate:
            type: float
        discountProfileId:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
