Pasteque\Bundle\ServerBundle\Entity\Ticket\SharedTicket:
    type: entity
    manyToOne:
        customerId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Customer
            joinColumn:
                name: customer_id
                referencedColumnName: id
        tariffAreaId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\TariffArea\TariffArea
            joinColumn:
                name: tariffarea_id
                referencedColumnName: id
        discountProfileId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Discount\DiscountProfile
            joinColumn:
                name: discountprofile_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Ticket\SharedTicketRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        name:
            type: string
            length: 255
        customerId:
            type: string
            length: 255
            nullable: true
        customerCount:
            type: integer
            nullable: true
        tariffAreaId:
            type: integer
            nullable: true
        discountProfileId:
            type: integer
            nullable: true
        discountRate:
            type: float
            nullable: true
    lifecycleCallbacks: {  }
