Pasteque\Bundle\ServerBundle\Entity\Ticket\TicketLine:
    type: entity
    manyToOne:
        ticketId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Ticket\Ticket
            joinColumn:
                name: ticket_id
                referencedColumnName: id
        productId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Product\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
        attributeSetInstanceId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Attribute\AttributeSetInstance
            joinColumn:
                name: attributesetinstance_id
                referencedColumnName: id
        taxId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Tax\Tax
            joinColumn:
                name: tax_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Ticket\TicketLineRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ticketId:
            type: string
            length: 255
        line:
            type: integer
        productId:
            type: string
            length: 255
            nullable: true
        attributeSetInstanceId:
            type: string
            length: 255
            nullable: true
        quantity:
            type: float
        price:
            type: float
        taxId:
            type: string
            length: 255
        discountRate:
            type: float
        attributes:
            type: blob
            nullable: true
        productLabel:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
