Pasteque\Bundle\ServerBundle\Entity\Ticket\Ticket:
    type: entity
    manyToOne:
        receiptId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Ticket\Receipt
            joinColumn:
                name: receipt_id
                referencedColumnName: id
        userId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        customerId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Customer
            joinColumn:
                name: customer_id
                referencedColumnName: id
        tariffAreaId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\TariffArea\TariffArea
            joinColumn:
                name: tariffarea_id
                referencedColumnName: id
        discountProfileId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Discount\DiscountProfile
            joinColumn:
                name: discountprofile_id
                referencedColumnName: id
    table: null
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\Ticket\TicketRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: integer
        date:
            type: datetime
            nullable: true
        status:
            type: integer
        customerCount:
            type: integer
            nullable: true
        discountRate:
            type: float
        discountProfileId:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
