Pasteque\Bundle\ServerBundle\Entity\User:
    type: entity
    manyToOne:
        roleId:
            targetEntity: Pasteque\Bundle\ServerBundle\Entity\Role
            inversedBy: users
            joinColumn:
                name: role_id
                referencedColumnName: id
    table: fos_user
    repositoryClass: Pasteque\Bundle\ServerBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        displayId:
            type: string
            length: 255
        roleId:
            type: string
            length: 255
        card:
            type: string
            length: 255
            nullable: true
        image:
            type: blob
            nullable: true
        visible:
            type: boolean
        addedDate:
            type: datetime
        addedBy:
            type: string
            length: 255
        updatedDate:
            type: datetime
            nullable: true
        updatedBy:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
