<?php

namespace Pasteque\Bundle\ServerBundle\Repository\TariffArea;

/**
 * TariffAreaRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
