<?php

namespace Pasteque\Bundle\ServerBundle\Repository\TariffArea;

/**
 * TariffAreaPriceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffAreaPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
