pasteque_api:
    resource: "@PastequeAPIBundle/Resources/config/routing.yml"
    prefix:   /

pasteque_server:
    resource: "@PastequeServerBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc