floor_api_get:
    path: /place/get/{id}
    defaults: { _controller: PastequeServerBundle:Floor:get }

floor_api_getAll:
    path: /place/getAll/
    defaults: { _controller: PastequeServerBundle:Floor:getAll }

floor_api_create:
    path: /floor/create
    defaults: { _controller: PastequeServerBundle:floor:create }

floor_api_update:
    path: /floor/update/{id}
    defaults: { _controller: PastequeServerBundle:floor:update }

floor_api_delete:
    path: /floor/delete/{id}
    defaults: { _controller: PastequeServerBundle:floor:delete }