floor_api_get:
    path: /place/get/{id}
    defaults: { _controller: PastequeServerBundle:Floor:get }

floor_api_getAll:
    path: /place/getAll/
    defaults: { _controller: PastequeServerBundle:Floor:getAll }
