location_api_get:
    path: /location/get/{id}
    defaults: { _controller: PastequeServerBundle:Location:get }

location_api_getAll:
    path: /location/getAll/
    defaults: { _controller: PastequeServerBundle:Location:getAll }

location_api_create:
    path: /location/create
    defaults: { _controller: PastequeServerBundle:location:create }

location_api_update:
    path: /location/update/{id}
    defaults: { _controller: PastequeServerBundle:location:update }

location_api_delete:
    path: /location/delete/{id}
    defaults: { _controller: PastequeServerBundle:location:delete }