
product_api_get:
    path: /product/get/{type}/{id}
    defaults: { _controller: PastequeServerBundle:Product:get }
    requirements:
      type:  product|ref|code

      
product_api_getAll:
    path: /product/getAll/{all}
    defaults: { _controller: PastequeServerBundle:Product:getAll }

product_api_getCategory:
    path: /product/getCategory/{categoryId}
    defaults: { _controller: PastequeServerBundle:Product:getCategory }

