user_api_get:
    path: /user/get/{id}
    defaults: { _controller: PastequeServerBundle:User:get }

user_api_getAll:
    path: /user/getAll/
    defaults: { _controller: PastequeServerBundle:User:getAll }
