<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Discount;

/**
 * DiscountProfileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
