<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Tax;

/**
 * TaxCustomerCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxCustomerCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
