<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Tax;

/**
 * TaxCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
