cash_api_get:
    path: /cash/get/{type}/{id}
    defaults: { _controller: PastequeServerBundle:Cash/Cash:get }
    requirements:
      type:  cash|cashRegister

cash_api_update:
    path: /cash/update/{id}
    defaults: { _controller: PastequeServerBundle:Cash/Cash:update }

cash_api_search:
    path: /cash/search/{cashRegisterId}/{dateStart}/{dateStop}
    defaults: { _controller: PastequeServerBundle:Cash/Cash:search, cashRegisterId: -1, dateStart: -1, dateStop: -1 }

cash_api_zticket:
    path: /cash/zticket/{id}
    defaults: { _controller: PastequeServerBundle:Cash/Cash:zticket }

cash_api_create:
    path: /cash/create
    defaults: { _controller: PastequeServerBundle:Cash/Cash:create }

cash_api_delete:
    path: /cash/delete/{id}
    defaults: { _controller: PastequeServerBundle:Cash/Cash:delete }
