cashRegister_api_get:
    path: /cashRegister/get/{type}/{id}
    defaults: { _controller: PastequeServerBundle:Cash/CashRegister:get }
    requirements:
      type:  type|id

cashRegister_api_getAll:
    path: /cashRegister/getAll/
    defaults: { _controller: PastequeServerBundle:Cash/CashRegister:getAll }

cash_api_create:
    path: /cash/create
    defaults: { _controller: PastequeServerBundle:Cash/CashRegister:create }

cash_api_update:
    path: /cash/update/{id}
    defaults: { _controller: PastequeServerBundle:Cash/CashRegister:update }

cash_api_delete:
    path: /cash/delete/{id}
    defaults: { _controller: PastequeServerBundle:Cash/CashRegister:delete }