<?php

namespace Pasteque\Bundle\ServerBundle\Repository;

/**
 * ThirdPartyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThirdPartyRepository extends \Doctrine\ORM\EntityRepository
{
}
