<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Stock;

/**
 * InventoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryRepository extends \Doctrine\ORM\EntityRepository
{
}
