<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Stock;

/**
 * StockLevelRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
