<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Stock;

/**
 * StockMoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockMoveRepository extends \Doctrine\ORM\EntityRepository
{
}
