<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Group;

/**
 * SubGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
