attribute:
    resource: '@PastequeServerBundle/Resources/config/attribute.routing.yml'

cash:
    resource: '@PastequeServerBundle/Resources/config/casg.routing.yml'

category:
    resource: '@PastequeServerBundle/Resources/config/category.routing.yml'

currency:
    resource: '@PastequeServerBundle/Resources/config/currency.routing.yml'

customer:
    resource: '@PastequeServerBundle/Resources/config/customer.routing.yml'

discount:
    resource: '@PastequeServerBundle/Resources/config/discount.routing.yml'

group:
    resource: '@PastequeServerBundle/Resources/config/group.routing.yml'

image:
    resource: '@PastequeServerBundle/Resources/config/image.routing.yml'

location:
    resource: '@PastequeServerBundle/Resources/config/location.routing.yml'

payment:
    resource: '@PastequeServerBundle/Resources/config/payment.routing.yml'

place:
    resource: '@PastequeServerBundle/Resources/config/place.routing.yml'

product:
    resource: '@PastequeServerBundle/Resources/config/product.routing.yml'

provider:
    resource: '@PastequeServerBundle/Resources/config/provider.routing.yml'

resource:
    resource: '@PastequeServerBundle/Resources/config/resource.routing.yml'

role:
    resource: '@PastequeServerBundle/Resources/config/role.routing.yml'

stock:
    resource: '@PastequeServerBundle/Resources/config/stock.routing.yml'

tariffArea:
    resource: '@PastequeServerBundle/Resources/config/tariffArea.routing.yml'

tax:
    resource: '@PastequeServerBundle/Resources/config/tax.routing.yml'

ticket:
    resource: '@PastequeServerBundle/Resources/config/ticket.routing.yml'

user:
    resource: '@PastequeServerBundle/Resources/config/user.routing.yml'

version:
    resource: '@PastequeServerBundle/Resources/config/version.routing.yml'