# Routes template : "name_api_methode:"
# URL template "path:/api/methode/{argument}
attribute_api_get:
    path: /attribute/get/{id}
    defaults: { _controller: PastequeServerBundle:Attribute:get }

attribute_api_getAll:
    path: /attribute/getAll
    defaults: { _controller: PastequeServerBundle:Attribute:getAll }

cash_api_get:
    path: /cash/get/{type}/{id}
    defaults: { _controller: PastequeServerBundle:Cash:get }
    requirements:
      type:  cash|cashRegister

cash_api_update:
    path: /cash/update/{id}
    defaults: { _controller: PastequeServerBundle:Cash:update }

cash_api_search:
    path: /cash/search/{cashRegisterId}/{dateStart}/{dateStop}
    defaults: { _controller: PastequeServerBundle:Cash:search, cashRegisterId: -1, dateStart: -1, dateStop: -1 }

cash_api_zticket:
    path: /cash/zticket/{id}
    defaults: { _controller: PastequeServerBundle:Cash:zticket }

cashMovement_api_move:
    path: /cashMovement/move/{id}/{date}/{payment}/{note}
    defaults: { _controller: PastequeServerBundle:cashMovement:get }

cashRegisters_api_get:
    path: /cashRegister/get/{type}/{id}
    defaults: { _controller: PastequeServerBundle:cashRegisters }
    requirements:
      type:  type|id

cashRegister_api_getAll:
    path: /cashRegister/getAll/
    defaults: { _controller: PastequeServerBundle:cashRegister:getAll }

category_api_get:
    path: /category/get/{id}
    defaults: { _controller: PastequeServerBundle:category:get }

category_api_getChildren:
    path: /category/getChildren/{parentId}
    defaults: { _controller: PastequeServerBundle:category:getChildren }

category_api_getAll:
    path: /category/getAll/
    defaults: { _controller: PastequeServerBundle:category:getAll }

group_api_getAll:
    path: /group/getAll/
    defaults: { _controller: PastequeServerBundle:group:getAll }

currency_api_get:
    path: /currency/get/{id}
    defaults: { _controller: PastequeServerBundle:currency:get }

currency_api_getMain:
    path: /currency/getMain/
    defaults: { _controller: PastequeServerBundle:currency:getMain }

currency_api_getAll:
    path: /currencies/getAll/
    defaults: { _controller: PastequeServerBundle:currency:getAll }

customer_api_get:
    path: /customer/get/{id}
    defaults: { _controller: PastequeServerBundle:customer:get }

customer_api_getAll:
    path: /customers/getAll/
    defaults: { _controller: PastequeServerBundle:customer:getAll }

customer_api_getTop:
    path: /customers/getTop/{limit}
    defaults: { _controller: PastequeServerBundle:customer:getTop, limit: 10 }

customer_api_addPrepaid:
    path: /customer/addPrepaid/{id}/{amount}
    defaults: { _controller: PastequeServerBundle:customer:addPrepaid }

# TODO a voir dans l'api de base
#customers_api_save:
#    path: /customers/save/{}

discount_api_get:
    path: /discount/get/{id}
    defaults: { _controller: PastequeServerBundle:discount:get }

discount_api_getAll:
    path: /discount/getAll/
    defaults: { _controller: PastequeServerBundle:discount:getAll }

discountProfile_api_getAll:
    path: /discountProfile/getAll/
    defaults: { _controller: PastequeServerBundle:discountProfile:getAll }

image_api_getPrd:
    path: /image/getPrd/{id}
    defaults: { _controller: PastequeServerBundle:image:getPrd }

image_api_getCat:
    path: /image/getCat/{id}
    defaults: { _controller: PastequeServerBundle:image:getCat }

image_api_getPm:
    path: /image/getPm/{id}
    defaults: { _controller: PastequeServerBundle:image:getPm }

image_api_getRes:
    path: /image/getRes/{label}
    defaults: { _controller: PastequeServerBundle:image:getRes }

location_api_get:
    path: /location/get/{id}
    defaults: { _controller: PastequeServerBundle:location:get }

location_api_getAll:
    path: /location/getAll/
    defaults: { _controller: PastequeServerBundle:location:getAll }

paymentMode_api_getAll:
    path: /paymentMode/getAll/
    defaults: { _controller: PastequeServerBundle:paymentMode:getAll }

places_api_get:
    path: /places/get/{id}
    defaults: { places: PastequeServerBundle:places:get }

place_api_getAll:
    path: /place/getAll/
    defaults: { places: PastequeServerBundle:place:getAll }

product_api_get:
    path: /product/get/{type}/{id}
    defaults: { _controller: PastequeServerBundle:product:get }
    requirements:
      type:  product|ref|code

provider_api_get:
    path: /provider/get/{id}
    defaults: { _controller: PastequeServerBundle:provider:get }

provider_api_getAll:
    path: /provider/getAll
    defaults: { _controller: PastequeServerBundle:provider:getAll }

product_api_getAll:
    path: /product/getAll/{all}
    defaults: { _controller: PastequeServerBundle:product:getAll }

product_api_getCategory:
    path: /product/getCategory/{categoryId}
    defaults: { _controller: PastequeServerBundle:product:getCategory }

ressource_api_get:
    path: /ressource/get/{label}
    defaults: { _controller: PastequeServerBundle:ressource:get }

role_api_get:
    path: /role/get/{id}
    defaults: { _controller: PastequeServerBundle:role:get }

role_api_getAll:
    path: /role/getAll/
    defaults: { _controller: PastequeServerBundle:role:getAll }

stock_api_getAll:
    path: /stock/getAll/{locationId}
    defaults: { _controller: PastequeServerBundle:stock:getAll }

tariffArea_api_getAll:
    path: /tariffArea/getAll/
    defaults: { _controller: PastequeServerBundle:tariffArea:getAll }

tax_api_get:
    path: /tax/get/{id}
    defaults: { _controller: PastequeServerBundle:tax:get }

tax_api_getAll:
    path: /tax/getAll/
    defaults: { _controller: PastequeServerBundle:tax:getAll }

ticket_api_getShared:
    path: /ticket/getShared/{id}
    defaults: { _controller: PastequeServerBundle:ticket:getShared }

ticket_api_getAllShared:
    path: /ticket/getAllShared/
    defaults: { _controller: PastequeServerBundle:ticket:getAllShared }

ticket_api_delShared:
    path: /tickets/delShared/{id}
    defaults: { _controller: PastequeServerBundle:ticket:delShared }

ticket_api_share:
    path: /ticket/share/{ticket}
    defaults: { _controller: PastequeServerBundle:ticket:share }

# TODO Methode save à verifier car les arguments sont des objets defins eux meme par des arguments
ticket_api_save:
    path: /ticket/save/{cashId}/{ticket}/{tickets}
    defaults: { _controller: PastequeServerBundle:ticket:save }

ticket_api_getAll:
    path: /ticket/getAll/
    defaults: { _controller: PastequeServerBundle:ticket:getAll }

tickets_api_get:
    path: /tickets/get/{id}
    defaults: { _controller: PastequeServerBundle:ticket:get }

ticket_api_getOpen:
    path: /ticket/getOpen/
    defaults: { _controller: PastequeServerBundle:ticket:getOpen }

ticket_api_search:
    path: /ticket/search/{ticketId}/{ticketType}/{cashId}/{dateStart}/{dateStop}/{customerId}/{userId}/{limit}
    defaults: { _controller: PastequeServerBundle:ticket:search, ticketId: -1, ticketType: -1, cashId: -1, dateStart: -1, dateStop: -1, customerId: -1, userId: -1, limit: -1 }

user_api_get:
    path: /user/get/{id}
    defaults: { _controller: PastequeServerBundle:user:get }

user_api_getAll:
    path: /user/getAll/
    defaults: { _controller: PastequeServerBundle:user:getAll }

user_api_updPwd:
    path: /user/updPwd/{id}/{oldPwd}/{newPwd}
    defaults: { _controller: PastequeServerBundle:user:updPwd }

# TODO api version à verifier
version_api_anyAction:
    path: /version/anyAction/
    defaults: { _controller: PastequeServerBundle:version:anyAction }
