attribute:
    resource: '@PastequeServerBundle/Resources/config/routing/attribute.routing.yml'

cash:
    resource: '@PastequeServerBundle/Resources/config/routing/cash/cash.routing.yml'

cashRegister:
    resource: '@PastequeServerBundle/Resources/config/routing/cash/cashRegister.routing.yml'

cashMovement:
    resource: '@PastequeServerBundle/Resources/config/routing/cash/cashMovement.routing.yml'

category:
    resource: '@PastequeServerBundle/Resources/config/routing/category.routing.yml'

currency:
    resource: '@PastequeServerBundle/Resources/config/routing/currency.routing.yml'

customer:
    resource: '@PastequeServerBundle/Resources/config/routing/customer.routing.yml'

discount:
    resource: '@PastequeServerBundle/Resources/config/routing/discount.routing.yml'

group:
    resource: '@PastequeServerBundle/Resources/config/routing/group.routing.yml'

image:
    resource: '@PastequeServerBundle/Resources/config/routing/image.routing.yml'

location:
    resource: '@PastequeServerBundle/Resources/config/routing/location.routing.yml'

payment:
    resource: '@PastequeServerBundle/Resources/config/routing/payment.routing.yml'

place:
    resource: '@PastequeServerBundle/Resources/config/routing/place.routing.yml'

product:
    resource: '@PastequeServerBundle/Resources/config/routing/product.routing.yml'

provider:
    resource: '@PastequeServerBundle/Resources/config/routing/provider.routing.yml'

resource:
    resource: '@PastequeServerBundle/Resources/config/routing/resource.routing.yml'

role:
    resource: '@PastequeServerBundle/Resources/config/routing/role.routing.yml'

stock:
    resource: '@PastequeServerBundle/Resources/config/routing/stock.routing.yml'

tariffArea:
    resource: '@PastequeServerBundle/Resources/config/routing/tariffArea.routing.yml'

tax:
    resource: '@PastequeServerBundle/Resources/config/routing/tax.routing.yml'

ticket:
    resource: '@PastequeServerBundle/Resources/config/routing/ticket.routing.yml'

user:
    resource: '@PastequeServerBundle/Resources/config/routing/user.routing.yml'

version:
    resource: '@PastequeServerBundle/Resources/config/routing/version.routing.yml'
