<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Ticket;

/**
 * SharedTicketLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedTicketLineRepository extends \Doctrine\ORM\EntityRepository
{
}
