<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Ticket;

/**
 * TicketLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketLineRepository extends \Doctrine\ORM\EntityRepository
{
}
