<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Ticket;

/**
 * ZTicketRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
