<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Payment;

/**
 * PaymentModeReturnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentModeReturnRepository extends \Doctrine\ORM\EntityRepository
{
}
