<?php

namespace Pasteque\Bundle\ServerBundle\Repository\Payment;

/**
 * PaymentModeValueRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentModeValueRepository extends \Doctrine\ORM\EntityRepository
{
}
